- type: antag
  id: Slasher
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: true
  objective: roles-antag-space-ninja-objective
  guides: [ SpaceNinja ]



#Maints Slasher Gear
- type: startingGear
  id: Slashergear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    back: ClothingBackpackSatchel
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinja
    id: AgentIDCard
    ears: ClothingHeadsetGrey
    pocket1: SpiderCharge
    pocket2: PinpointerStation
    belt: EnergyKatana
  inhand:
    - MacheteAntag
  storage:
    back: # belt holds katana so satchel has the tools for sabotaging things
    - JawsOfLife
    - PipeBomb
    - PipeBomb
    - WelderIndustrial
    - Emag


